"""The PLATO mark and the typography that goes with it.

The logo is an SVG (``assets/logo.svg``) rather than a PNG so it stays crisp
at every size the app needs it -- a 32 px window icon, a 96 px empty-state
mark, a 256 px taskbar tile -- from one file. It is generated by
``scripts/make_logo.py``, which draws the 12x8 grid parametrically; edit that
and regenerate rather than hand-editing the SVG.

Typography is a *stack*, not a single family, because a font that is not
installed silently falls back to something arbitrary. Each stack lists the
faces in preference order and ends at a generic family, so the app has a
defined appearance on any machine.
"""

from __future__ import annotations

from pathlib import Path

from PySide6.QtCore import QSize, Qt
from PySide6.QtGui import QColor, QIcon, QImage, QPainter, QPixmap

ASSETS = Path(__file__).parent / "assets"
LOGO_SVG = ASSETS / "logo.svg"

# Display face for the wordmark and headings.
#
# Gill Sans is the humanist sans this mark was designed against: its wide,
# classical proportions suit the geometric plate, and it ships with Office so
# it is present on the machines this runs on. The fallbacks walk down through
# other humanist sans faces before reaching the generic.
DISPLAY_STACK = '"Gill Sans MT", "Gill Sans", Optima, Candara, "Segoe UI", sans-serif'

# Body face. Segoe UI is the system face and the one the rest of the GUI
# already renders in; keeping body text on it means the display face reads as
# a deliberate accent rather than a second competing voice.
BODY_STACK = '"Segoe UI", -apple-system, "Helvetica Neue", Arial, sans-serif'

# Serif, for the few places a figure caption wants one.
SERIF_STACK = '"Palatino Linotype", Palatino, "Book Antiqua", Georgia, serif'

# Letter-spacing for the wordmark, in em. The mark is five wide capitals; at
# normal tracking they crowd, and the logo reads as a word rather than a mark.
WORDMARK_TRACKING = 0.18


def logo_pixmap(size: int) -> QPixmap:
    """Render the logo at ``size`` px square.

    Returns an empty pixmap if the asset or the SVG module is missing, so a
    broken asset costs the app its logo and nothing else.
    """
    try:
        from PySide6.QtSvg import QSvgRenderer
    except ImportError:  # pragma: no cover - Qt built without SVG support
        return QPixmap()
    if not LOGO_SVG.exists():
        return QPixmap()

    renderer = QSvgRenderer(str(LOGO_SVG))
    if not renderer.isValid():
        return QPixmap()

    image = QImage(size, size, QImage.Format.Format_ARGB32)
    image.fill(Qt.GlobalColor.transparent)
    painter = QPainter(image)
    painter.setRenderHint(QPainter.RenderHint.Antialiasing, True)
    renderer.render(painter)
    painter.end()
    return QPixmap.fromImage(image)


def app_icon() -> QIcon:
    """The window/taskbar icon, at the sizes Windows actually asks for."""
    icon = QIcon()
    for size in (16, 24, 32, 48, 64, 128, 256):
        pixmap = logo_pixmap(size)
        if not pixmap.isNull():
            icon.addPixmap(pixmap)
    return icon
