"""The PLATO mark and the typography that goes with it.

The logo is an SVG (``assets/logo.svg``) rather than a PNG so it stays crisp
at every size the app needs it -- a 32 px window icon, a 96 px empty-state
mark, a 256 px taskbar tile -- from one file. It is generated by
``scripts/make_logo.py``, which draws the 12x8 grid parametrically; edit that
and regenerate rather than hand-editing the SVG.

Typography is a *stack*, not a single family, because a font that is not
installed silently falls back to something arbitrary. Each stack lists the
faces in preference order and ends at a generic family, so the app has a
defined appearance on any machine.
"""

from __future__ import annotations

from pathlib import Path

from PySide6.QtCore import QSize, Qt
from PySide6.QtGui import QColor, QIcon, QImage, QPainter, QPixmap

ASSETS = Path(__file__).parent / "assets"
LOGO_SVG = ASSETS / "logo.svg"

# Display face for the wordmark, tab bar and panel headings.
#
# Bahnschrift is Microsoft's DIN -- an industrial grotesque with the flat
# terminals and open counters that suit a mark built from a plate grid. It is
# a Windows system font, so it is present on the machines this runs on, and
# the fallbacks walk down through other DIN-adjacent grotesques before
# reaching the generic.
DISPLAY_STACK = (
    '"Bahnschrift", "DIN Next", "Roboto Condensed", "Segoe UI", sans-serif'
)

# Body face. Left on the system UI face: the display face reads as a
# deliberate accent only while everything around it does not compete.
BODY_STACK = '"Segoe UI", -apple-system, "Helvetica Neue", Arial, sans-serif'

# Serif, for figure captions and anything that wants to read as prose.
# Cambria was designed for screen reading at small sizes, which is what a
# caption under a micrograph is.
SERIF_STACK = '"Cambria", "Georgia", "Palatino Linotype", serif'

# Letter-spacing for the wordmark, in em. The mark is five wide capitals; at
# normal tracking they crowd, and the logo reads as a word rather than a mark.
WORDMARK_TRACKING = 0.18


def logo_pixmap(size: int) -> QPixmap:
    """Render the logo at ``size`` px square.

    Returns an empty pixmap if the asset or the SVG module is missing, so a
    broken asset costs the app its logo and nothing else.
    """
    try:
        from PySide6.QtSvg import QSvgRenderer
    except ImportError:  # pragma: no cover - Qt built without SVG support
        return QPixmap()
    if not LOGO_SVG.exists():
        return QPixmap()

    renderer = QSvgRenderer(str(LOGO_SVG))
    if not renderer.isValid():
        return QPixmap()

    # Render at the display's true pixel density, not at logical size. On a
    # 150% or 200% display Qt scales a logical-size pixmap up to fill the
    # space, which is exactly the blur an SVG exists to avoid. Drawing at
    # size x ratio and tagging the pixmap with that ratio makes Qt lay it out
    # at `size` points while showing every physical pixel.
    ratio = _device_ratio()
    physical = max(1, int(round(size * ratio)))

    image = QImage(physical, physical, QImage.Format.Format_ARGB32)
    image.fill(Qt.GlobalColor.transparent)
    painter = QPainter(image)
    painter.setRenderHint(QPainter.RenderHint.Antialiasing, True)
    painter.setRenderHint(QPainter.RenderHint.SmoothPixmapTransform, True)
    renderer.render(painter)
    painter.end()

    pixmap = QPixmap.fromImage(image)
    pixmap.setDevicePixelRatio(ratio)
    return pixmap


def _device_ratio() -> float:
    """The current display's pixel ratio, or 1.0 with no application yet.

    Read live rather than cached: the app can be moved to a second monitor
    with a different scaling factor.
    """
    from PySide6.QtWidgets import QApplication

    app = QApplication.instance()
    if app is None:
        return 1.0
    screen = app.primaryScreen()
    return float(screen.devicePixelRatio()) if screen is not None else 1.0


def app_icon() -> QIcon:
    """The window/taskbar icon, at the sizes Windows actually asks for.

    Rendered at 1:1 rather than through ``logo_pixmap``: a QIcon chooses
    between its pixmaps by physical size, so a ratio-tagged pixmap would make
    it pick the wrong one. 512 is included for the large tiles Windows uses
    in task switching and the store-style views.
    """
    icon = QIcon()
    for size in (16, 24, 32, 48, 64, 128, 256, 512):
        pixmap = _render(size)
        if not pixmap.isNull():
            icon.addPixmap(pixmap)
    return icon


def _render(size: int) -> QPixmap:
    """The logo at exactly ``size`` physical pixels, untagged."""
    try:
        from PySide6.QtSvg import QSvgRenderer
    except ImportError:  # pragma: no cover - Qt built without SVG support
        return QPixmap()
    if not LOGO_SVG.exists():
        return QPixmap()
    renderer = QSvgRenderer(str(LOGO_SVG))
    if not renderer.isValid():
        return QPixmap()

    image = QImage(size, size, QImage.Format.Format_ARGB32)
    image.fill(Qt.GlobalColor.transparent)
    painter = QPainter(image)
    painter.setRenderHint(QPainter.RenderHint.Antialiasing, True)
    renderer.render(painter)
    painter.end()
    return QPixmap.fromImage(image)
